### ISSUE TITLE
Add semverver CI

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#2570]
After 1.0 we have to be careful not to violate [semver requirements](https://doc.rust-lang.org/cargo/reference/semver.html). We can use the [`rust-semverver`](https://github.com/rust-lang/rust-semverver) tool to generate a report for each PR.

**Comment by robertbastian** [comment]
Alternatively there's this crate as well https://github.com/Enselic/cargo-public-api

**Comment by pdogr** [comment]
`rust-semver` errors out in some of our crates with the following errors
```
thread 'rustc' panicked at 'assertion failed: !self.in_new_crate(old)', src/mapping.rs:213:9
```
```
thread 'rustc' panicked at 'assertion failed: !value.has_escaping_bound_vars()', /rustc/4493a0f4724c0bae1436242d76cccc9c0a287b80/compiler/rustc_middle/src/ty/sty.rs:1024:9
```

**Comment by robertbastian** [comment]
Hmm I remember seeing that `has_escaping_bound_vars` regularly a while ago. Is your toolchain up to date? Can you try running with nightly?

**Comment by sffc** [comment]
Discussion:

- Run the tool manually for the 1.1 release
- Revisit CI for it in a future release

**Comment by sffc** [comment]
- @Manishearth - It's tricky to run semverver on CI, because we need to match it to a specific rustc version. It might involve adding another nightly. It is intended to be hands-off, and it is not supposed to be too expensive. What we could do is run it on cron job CI to keep the number of main CI jobs low.

**Comment by Manishearth** [comment]
Fixed by #6619
