### ISSUE TITLE
ListFormatter 1.1 panics in Spanish locale

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3048]
Given the following code:

```rust
use icu::list::ListFormatter;
use icu::list::ListLength;
use icu::locid::locale;
use lazy_static::lazy_static;

lazy_static! {
    static ref SPANISH_LIST_FORMATTER: ListFormatter =
        ListFormatter::try_new_and_with_length_unstable(
            &icu_testdata::unstable(),
            &locale!("es").into(),
            ListLength::Wide
        )
        .expect("Locale 'es' is present in testdata");
}

fn main() {
    let result = SPANISH_LIST_FORMATTER.format_to_string(["uno", "dos", "tres"].iter());
    assert_eq!(result, "uno, dos y tres");
    println!("{}", result);
}
```

I get the following error with stack trace:

```
thread 'main' panicked at 'byte index 2 is out of bounds of `,`', library/core/src/str/mod.rs:107:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::str::slice_error_fail_rt
   3: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
   4: core::intrinsics::const_eval_select
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/intrinsics.rs:2361:5
   5: core::str::slice_error_fail
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/str/mod.rs:86:9
   6: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/str/traits.rs:218:21
   7: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/str/traits.rs:65:9
   8: icu_list::patterns::<impl icu_list::provider::ListJoinerPattern>::borrow_tuple
             at /usr/local/google/home/sffc/.cargo/registry/src/github.com-1ecc6299db9ec823/icu_list-1.1.0/src/patterns.rs:152:14
   9: icu_list::patterns::<impl icu_list::provider::ConditionalListJoinerPattern>::parts
             at /usr/local/google/home/sffc/.cargo/registry/src/github.com-1ecc6299db9ec823/icu_list-1.1.0/src/patterns.rs:96:18
  10: <icu_list::list_formatter::FormattedList<W,I> as writeable::Writeable>::write_to_parts
             at /usr/local/google/home/sffc/.cargo/registry/src/github.com-1ecc6299db9ec823/icu_list-1.1.0/src/list_formatter.rs:183:60
  11: writeable::Writeable::write_to
             at /usr/local/google/home/sffc/.cargo/registry/src/github.com-1ecc6299db9ec823/writeable-0.5.1/src/lib.rs:208:9
  12: writeable::Writeable::write_to_string
             at /usr/local/google/home/sffc/.cargo/registry/src/github.com-1ecc6299db9ec823/writeable-0.5.1/src/lib.rs:270:17
  13: icu_list::list_formatter::ListFormatter::format_to_string
             at /usr/local/google/home/sffc/.cargo/registry/src/github.com-1ecc6299db9ec823/icu_list-1.1.0/src/list_formatter.rs:124:9
  14: demo::main
             at ./lazy_static/src/main.rs:25:18
  15: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
```

The code is:

```rust
    fn borrow_tuple(&'data self) -> PatternParts<'data> {
        #![allow(clippy::indexing_slicing)] // by invariant
        let index_0 = self.index_0 as usize;
        let index_1 = self.index_1 as usize;
        (
            &self.string[0..index_0],
            &self.string[index_0..index_1],
            &self.string[index_1..],
        )
    }
```

Seems the stated invariant is not being upheld somewhere?

CC @robertbastian

**Comment by robertbastian** [comment]
I cannot reproduce this. Your stack trace tries to slice `","[0..2]`, but the baked data does not contain the string `","`, only `", "`: https://github.com/unicode-org/icu4x/blob/main/provider/testdata/data/baked/list/and_v1/es.rs.data

**Comment by robertbastian** [comment]
Oh boi, I know why this is happening. I globally replaced ", " by "," to cut down on data size in all the byte arrays for the release. I'll do a patch release without any changes now that we have the 20MB limit.

**Comment by sffc** [comment]
Hmm, I was going to say that even if there is invalid data, we shouldn't panic, but this is invalid _baked_ data. :boom:

**Comment by robertbastian** [comment]
If we want to be panic free even in the presence of unsafe f-ups, we need to replace all our indexing by `.get_unchecked`. Then we'll get UB but continue running :)

**Comment by sffc** [comment]
I agree that panic is better than

> unsafe f-ups
