### ISSUE TITLE
Add CI check for bincode support

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#491]
We should add a CI check that makes sure testdata can be built into bincode as well as into json.  This should help catch problems like forgetting to use the serialize_none feature in data structs.

**Comment by gregtatum** [comment]
Building the bincode:

```sh
cargo run
  --features export-bin       /
  --features bincode          /
  --features serialize_none   /
  --                          /
  --cldr-tag 38.1.0           /
  --out ./icu4x-data          /
  --all-keys                  /
  -s bincode
```

**Comment by gregtatum** [comment]
This appears to work even when forgetting the `serialize_none` check in #480.

**Comment by gregtatum** [comment]
In fact, it appears that the `serialize_none` feature is frequently forgotten already:

https://github.com/unicode-org/icu4x/blob/master/components/datetime/src/provider/mod.rs#L20-L23

**Comment by sffc** [comment]
It works when writing, but do the tests pass when reading the data?

Tip: build the data as Bincode as you did, and then run the tests with `ICU4X_TESTDATA_DIR` as described here:

https://github.com/unicode-org/icu4x/tree/master/resources/testdata#pointing-to-custom-test-data

**Comment by sffc** [comment]
Also see: #335

**Comment by gregtatum** [comment]
I had a complete misunderstanding of the `serialize_none` feature. I didn't realize it meant "serialize the none type of an Option". I assumed it meant something like "do not serialize". Turns out my comments above are misunderstood.

**Comment by gregtatum** [comment]
I can't get the bincode tests to pass on the master branch. I'm not sure if it's me, or if it's everywhere.

### Steps to reproduce:

```sh
cd components/provider_fs
```

```sh
cargo run                     \
  --features export-bin       \
  --features bincode          \
  --features serialize_none   \
  --                          \
  --cldr-tag 38.1.0           \
  --out ./icu4x-data          \
  --all-keys                  \
  -s bincode
```

```sh
cd ../..
```

```sh
RUST_BACKTRACE=1 ICU4X_TESTDATA_DIR=~/dev/icu4x/components/provider_fs/icu4x-data cargo test
```

This results in:

```
---- src/lib.rs - (line 13) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Resource(UnknownSyntax(Bincode))', src/lib.rs:20:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
   4: rust_out::main::_doctest_main_src_lib_rs_13_0
   5: rust_out::main
   6: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Trying it for `icu_datetime` results in similar issues:

```
RUST_BACKTRACE=1 ICU4X_TESTDATA_DIR=~/dev/icu4x/components/provider_fs/icu4x-data cargo test -p icu_datetime
```

```
---- test_fixtures stdout ----
thread 'test_fixtures' panicked at 'called `Result::unwrap()` on an `Err` value: DataProvider(Resource(UnknownSyntax(Bincode)))', components/datetime/tests/datetime.rs:25:72
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/greg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: datetime::test_fixtures
             at ./tests/datetime.rs:25:19
   5: datetime::test_fixtures::{{closure}}
             at ./tests/datetime.rs:19:1
   6: core::ops::function::FnOnce::call_once
             at /Users/greg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_dayperiod_patterns stdout ----
thread 'test_dayperiod_patterns' panicked at 'called `Result::unwrap()` on an `Err` value: Resource(UnknownSyntax(Bincode))', components/datetime/tests/datetime.rs:62:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/greg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: datetime::test_dayperiod_patterns
             at ./tests/datetime.rs:52:38
   5: datetime::test_dayperiod_patterns::{{closure}}
             at ./tests/datetime.rs:46:1
   6: core::ops::function::FnOnce::call_once
             at /Users/greg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sffc** [comment]
You need to enable the bincode option when you run the tests, too...

**Comment by filmil** [comment]
> You need to enable the bincode option when you run the tests, too...

Hm, it may be useful then to have a test that would fail with a clear error message when bincode is required but not used.  I know that one can deduce the root cause from the backtraces, but I've come to a realization that we want to limit the number of puzzles we must solve on a daily basis.

(Sorry for being away for a while, and this belated suggestion... as always, it's put here in the hope it's useful, but feel free to disregard)

**Comment by gregtatum** [comment]
I suspect things aren't working as expected, unless I'm missing something.

First, naively running:

```sh
➤ RUST_BACKTRACE=1 ICU4X_TESTDATA_DIR=~/dev/icu4x/components/provider_fs/icu4x-data cargo test --features bincode

error: --features is not allowed in the root of a virtual workspace
```

Then going into the icu_datetime crate:

```sh
➤ cd components/datetime
➤ RUST_BACKTRACE=1 ICU4X_TESTDATA_DIR=~/dev/icu4x/components/provider_fs/icu4x-data cargo test --features bincode

error: Package `icu_datetime v0.1.0 (/Users/greg/dev/icu4x/components/datetime)` does not have the feature `bincode`
```

Manually adding the `bincode` feature to the feature list in `components/datetime/Cargo.toml` still results in the same `UnknownSyntax(Bincode)` error:

```sh
➤ RUST_BACKTRACE=1 ICU4X_TESTDATA_DIR=~/dev/icu4x/components/provider_fs/icu4x-data cargo test --features bincode

running 2 tests
test test_fixtures ... FAILED
test test_dayperiod_patterns ... FAILED

failures:

---- test_fixtures stdout ----
thread 'test_fixtures' panicked at 'called `Result::unwrap()` on an `Err` value: DataProvider(Resource(UnknownSyntax(Bincode)))', components/datetime/tests/datetime.rs:25:72
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/greg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: datetime::test_fixtures
             at ./tests/datetime.rs:25:19
   5: datetime::test_fixtures::{{closure}}
             at ./tests/datetime.rs:19:1
   6: core::ops::function::FnOnce::call_once
             at /Users/greg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_dayperiod_patterns stdout ----
thread 'test_dayperiod_patterns' panicked at 'called `Result::unwrap()` on an `Err` value: Resource(UnknownSyntax(Bincode))', components/datetime/tests/datetime.rs:62:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/greg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: datetime::test_dayperiod_patterns
             at ./tests/datetime.rs:52:38
   5: datetime::test_dayperiod_patterns::{{closure}}
             at ./tests/datetime.rs:46:1
   6: core::ops::function::FnOnce::call_once
             at /Users/greg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_dayperiod_patterns
    test_fixtures

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s
```

**Comment by sffc** [comment]
I wish Rust would allow you to enable features across a workspace.

To fix it, you should be able to edit `resources/testdata/Cargo.toml` as follows:

```toml
# Old:
icu_provider_fs = { version = "0.1", path = "../../components/provider_fs" }

# New:
icu_provider_fs = { version = "0.1", path = "../../components/provider_fs", features = ["bincode"] }
```

I guess the only other way to enable this for testing would be to explicitly add "bincode" as a feature of every single component crate. 😞

**Comment by sffc** [comment]
Also, the error message could be better.  I have `fmt::Display` implemented with more helpful information (suggesting that you need to enable the feature), but all the outputs you pasted above are using the `fmt::Debug` implementation of the error message. 😕  @Manishearth

**Comment by Manishearth** [comment]
We should just manually implement Debug: If anything Debug should always have more information

**Comment by sffc** [comment]
Do you recommend making Debug for error types produce the same string as what I've been putting as Display?

**Comment by Manishearth** [comment]
Debug basically should have as much information as possible, so yes, if you're customizing Display, you should call it from Debug too, _unless your Display implementation loses information_, in which case your Debug impl should either be the auto derive or something custom that contains that info as well.

**Comment by sffc** [comment]
The amount of *information* in Debug and Display is the same; it's just that Display glues it together more nicely, using a format string that explains what the different pieces mean.

Hopefully the Debug vs Display question will become obsolete when we implement #298.
