### ISSUE TITLE
Failing debug_assert when formatting week_of_year

### ISSUE THREAD

**Issue by iyzana** [unicode-org/icu4x#4977]
Formatting the first 13 days of the year fails when including the week_of_year.

## Steps to reproduce

Run the following code in debug-mode (i.e. `cargo run` without --release)

```rust
use icu_calendar::{DateTime, Gregorian, Time};
use icu_datetime::options::components;
use icu_datetime::TypedDateTimeFormatter;
use icu_locid::locale;

fn main() {
    let mut elements = components::Bag::empty();
    elements.week = Some(components::Week::NumericWeekOfYear);
    let formatter = TypedDateTimeFormatter::<Gregorian>::try_new_experimental(
        &locale!("en_US").into(),
        elements.into(),
    )
    .expect("valid formatter");
    let date = icu_calendar::Date::try_new_gregorian_date(2024, 1, 1).expect("valid date");
    formatter.format_to_string(&DateTime::new(date, Time::midnight()));
}
```

## Expected behaviour

The formatter formats the date to "1"

## Actual behaviour

The program panics on `format_to_string`

```
thread 'main' panicked at .local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/icu_datetime-1.5.0/src/input.rs:352:9:
assertion failed: day_of_year_info.day_of_year >= icu_calendar::week::MIN_UNIT_DAYS
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:145:5
   3: icu_datetime::input::ExtractedDateTimeInput::week_of_year
             at .local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/icu_datetime-1.5.0/src/input.rs:352:9
   4: icu_datetime::format::datetime::try_write_field::{{closure}}
             at .local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/icu_datetime-1.5.0/src/format/datetime.rs:531:21
   5: core::result::Result<T,E>::and_then
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1321:22
   6: icu_datetime::format::datetime::try_write_field
             at .local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/icu_datetime-1.5.0/src/format/datetime.rs:528:39
   7: icu_datetime::format::datetime::try_write_pattern_items
             at .local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/icu_datetime-1.5.0/src/format/datetime.rs:246:27
   8: icu_datetime::format::datetime::try_write_pattern
             at .local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/icu_datetime-1.5.0/src/format/datetime.rs:212:5
   9: <icu_datetime::format::datetime::FormattedDateTime as writeable::Writeable>::write_to
             at .local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/icu_datetime-1.5.0/src/format/datetime.rs:131:19
  10: writeable::Writeable::write_to_string
             at .local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/writeable-0.5.5/src/lib.rs:279:17
  11: icu_datetime::datetime::TypedDateTimeFormatter<C>::format_to_string
             at .local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/icu_datetime-1.5.0/src/datetime.rs:788:9
  12: icu4x_reproduce::main
             at ./src/main.rs:15:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
```

## Versions

- icu_datetime version 1.5.0
- icu_calendar version 1.5.0
- icu_locid version 1.5.0
- rustc 1.78.0

**Comment by sffc** [comment]
`icu_datetime` version 1.5.1 has been released with this fix
